### ISSUE TITLE
CityLights not working [FIXED]

### ISSUE THREAD

**Issue by KevinClaytonGustafson** [KSP-RO/RSSVE#1]
In the newest version of RSSVE the city lights don't work without some tweaking. I had to add a citylights texture from an older version of RSSVE (not sure which one) and edited the city lights config. The file and the config are attached.

[RSSVE_CityLights_Fix.zip](https://github.com/KSP-RO/RSSVE/files/4340304/RSSVE_CityLights_Fix.zip)

**Comment by Theysen** [comment]
reimplemented with latest release 👍🏻

**Comment by KevinClaytonGustafson** [comment]
Thanks!
