### ISSUE TITLE
Earth clouds should be flipped horizontally

### ISSUE THREAD

**Issue by AndrewDraws** [KSP-RO/RSSVE#10]
This is something that has kind of bothered me for a while, but I'm almost certain that the clouds for Earth in RSSVE should be flipped horizontally. This is particularly obvious in the Andes, where the gap in the clouds where the Andes would be is very obviously mirrored. Below are some pictures indicating what I'm referring to:
![Screenshot (381)_LI](https://user-images.githubusercontent.com/17421431/112893017-b7a25100-909f-11eb-93e3-578c6e40b58a.jpg)
![earth_from_space_western_hemisphere_lg__87023 1560352971_LI](https://user-images.githubusercontent.com/17421431/112893103-d56fb600-909f-11eb-9c36-258bd176deca.jpg)

**Comment by Theysen** [comment]
Interesting catch. I think you might be right as that's a clear feature of Earth's topograpghy / meterology.

**Comment by AndrewDraws** [comment]
Planet textures have to be flipped horizontally as well (and vertically, if it's a dds file), so it makes sense that the same would have to be done for cloud textures

**Comment by NathanKell** [comment]
Flipped and then offset.
https://github.com/NathanKell/RealSolarSystem/wiki/PQS-Textures-and-Heightmaps

**Comment by Theysen** [comment]
fixed with #11
