### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by Baselet** [KSP-RO/RSSVE#15]
I'm going to the latest released version which is tagged 2.1.2, the title says 2.1.1, there is [1.10] in brackets which kinda hints at possibly being compatible with KSP 1.10.
Now the download has a RSSVE.version file in it saying I just got RSSVE version 1.5.0.1 which is compatible with KSP 1.4.0-1.7.3
The changelog ends at RSSVE v1.7.3-RC1 for KSP 1.7.3 (2020-01-28)

Is the download pointing at a wrong place? Is the .version file not updated? (if not, why not? Surely it's 30 seconds of work to do so I can't imagine anyone releasing something without changing the version tags?)

I genuinely can't tell what I just downloaded... It's really not supposed to be this hard is it or is my brain or browser broken?

**Comment by Theysen** [comment]
I'll do my best to improve it 💯
