### ISSUE TITLE
Incompatible with Unity 2019.4.18f1

### ISSUE THREAD

**Issue by lakesidewiseman** [KSP-RO/RSSVE#19]
While a new release was just pushed a few days ago, it seems that it is still incompatible with the latest version of KSP. I get the error on start and it says it is incompatible with version 1.12. Any chance you could update it to work with this version of Unity?

**Comment by Theysen** [comment]
when we switch the entire RO suite to 1.12, yes.

**Comment by RossComputerGuy** [comment]
I experience this issue and I just downloaded the mod.

**Comment by paulcobbaut** [comment]
I also get this message, both with 1.12.2 and 1.12.3 (Debian, Steam).
