### ISSUE TITLE
Update a new version to 1.8.1

### ISSUE THREAD

**Issue by Peter-JY** [KSP-RO/RSSVE#2]
More and more Mods become incompatible with 1.7.3,such as [Principia](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip151-161-17x-181-principia%E2%80%94version-fuchs-released-2020-05-22%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&do=findComment&comment=3788990) , so could you update RSSVE to 1.8.1, the version has the most Mods, and upload it to github?

**Comment by 13-potatos-why** [comment]
> More and more Mods become incompatible with 1.7.3,such as [Principia](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip151-161-17x-181-principia%E2%80%94version-fuchs-released-2020-05-22%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&do=findComment&comment=3788990) , so could you update RSSVE to 1.8.1, the version has the most Mods, and upload it to github?

Download rssve for 1.7.3 and replace plugin with "https://github.com/KSP-RO/RSSVE/blob/1.8%2B/RSSVE/Plugins/RSSVE.dll" this version

**Comment by Theysen** [comment]
done with latest release.
