### ISSUE TITLE
Trouble Downloading and Installing

### ISSUE THREAD

**Issue by playbyplay225** [KSP-RO/RSSVE#20]
I am having trouble when I download the .zip file, it says it's corrupted, then when I fix it using WinRAR and install RSSVE and its 1.12 update into KSP, it's not compatible with the latest version of Module Manager, and Unity version 2019.4.18f1.
Is there a way to fix the compatibility issues, or would it have to be something on the dev's end?
Screenshot below to show the error messages.
EDIT: Grammar
![image](https://user-images.githubusercontent.com/93497812/139607461-49d409e3-b42b-48ea-acf7-0d7deda4ea70.png)

**Comment by al2me6** [comment]
We don’t support 1.12 at this point in time, nor do we recommend manual installation (CKAN is preferred). 
Please downgrade to KSP 1.10 and install RSSVE using CKAN.
