### ISSUE TITLE
Issues with install instructions

### ISSUE THREAD

**Issue by auddie2015** [KSP-RO/RSSVE#27]
I did not have clouds so I came here to see if there was an issue. I saw that the instructions list very specific versions of addons to install, so I did. When I launch the game, a box pops up that says RSSVE is incompatible with 1.12.5. It works inside the game, though. Are the instructions still valid and just ignore the warning?

**Comment by marsh1832** [comment]
It’s a known bug for clouds to not appear on the main menu, but otherwise work.
