### ISSUE TITLE
Land on Earth disappears in map view

### ISSUE THREAD

**Issue by ajs117** [KSP-RO/RSSVE#3]
KSP 1.8.1

Mods:
- RSSVE 1.7.3-RC1_HR with 1.8 DLL
- scatterer 0.061
- EVE 1.8.0.2
- TUFX 1.0.2.3

![Kerbal Space Program 05_07_2020 13_13_32](https://user-images.githubusercontent.com/34308197/86532525-a3d80e80-bec2-11ea-817a-81035ad024a7.png)

**Comment by siimav** [comment]
Disable ambient occlusion in TUFX settings
