### ISSUE TITLE
mist (??????)

### ISSUE THREAD

**Issue by Xeonex3** [KSP-RO/RSSVE#5]
![screenshot11](https://user-images.githubusercontent.com/71473027/93540354-cc03d500-f929-11ea-9d03-24ca86e0f0fa.png)
 
this has been happening in 1.9.1 too, which is where RSS is at,, i use a branch of kopernicus that works for 1.10.1, however, this bug of there being this sort of fog has been happening in all the versions newer than 1.8.1.

**Comment by Theysen** [comment]
RSSVE is not developed or adapted to 1.9+ yet. Sorry.
