### ISSUE TITLE
Installation guide needs clarification

### ISSUE THREAD

**Issue by ezeeetm** [KSP-RO/RSSVE#7]
The RSSVE installation guide [here](https://github.com/KSP-RO/RSSVE/wiki/Installation-Guide)  seems to be geared towards game version 1.8.x.  The version of RSSE referenced is 1.8.1, and the version of EVE is 1.8.0, etc.

However, just about  everywhere else, the RSS ecosystem seems to be referencing 1.7.3

https://github.com/KSP-RO/RSSVE/tags
https://forum.kerbalspaceprogram.com/index.php?/topic/177216-173-real-solar-system-v164-26-nov-2019/

Including the RSS base mod itself:  https://github.com/KSP-RO/RealSolarSystem/releases/tag/v16.4

I'm guessing that what's happening here is that its possible to get RSS/RSSVE working on 1.8.1, but not all the other mods have caught up with the numbering/versioning.  

The install instructions should specify what version of KSP to use and/or have two verssions of the install instructions (one for 1.7.3, one for 1.8.1

If someone will confirm this and give some guidance, I will submit a PR with these changes.

**Comment by Theysen** [comment]
Do not rely on forums, source of truth is GitHub for everything related to RSS / RO and RP-1 :)
