### ISSUE TITLE
Graphical bug in RSSVE 

### ISSUE THREAD

**Issue by RaptorClaw26** [KSP-RO/RSSVE#9]
I was setting up a new RP-0/RP-1 career, and when i got to the visual mods, i installed it all and launched the game, but when i get to the KSC, this weird glitch appears, im sure its RSSVE, because i manually loaded and unloaded every graphic mod and run the game every time and only when i put RSSVE it happens, i tried with both versions, the HR and the LR, any thoughts??
![RSSVE bug](https://user-images.githubusercontent.com/78675465/107137748-34e9ea80-68d5-11eb-9f49-177da01b9c38.png)

**Comment by siimav** [comment]
If you followed the install guide and are on KSP 1.8.1, then make sure you're using Scatterer v0.0632.

**Comment by RaptorClaw26** [comment]
I have installed the version 0.0723, i imagine that it would be better but i would try

**Comment by RaptorClaw26** [comment]
It Actually Works!, thanks a lot, apparently it doesn´t work with the latest version of scatterer
